### ISSUE TITLE
parameter decorators for all functions

### ISSUE THREAD

**Issue by valoricDe** [rbuckton/proposal-class-method-parameter-decorators#5]
Hi, I am not deep into programming language semantics.

I know that decorators for all functions is currently not desired because it would not possible to hoist the functions.

But with function parameters this would be not the problem right?

**Comment by rbuckton** [comment]
Function parameter decorators would still cause issues with hoisting as they would still require an evaluation step and could reference variables in the outer scope. The hoisting issue is one of the areas we're investigating in https://github.com/tc39/proposal-function-and-object-literal-element-decorators.

This proposal is currently scoped to class elements and class constructors as those are the only two places that decorators are currently supported with confidence, given that the core Decorators proposal is at Stage 3. The plan is to extend parameter decorators to cover all function-like things that support decorators, and thus would seek to cover function and object literal methods as well if that proposal advances to Stage 2.
